 Marine VAN RENTERGHEM (31621700)  
# LMAPR1492 Physique des matériaux : Tâche 6 
Notebook permettant de télécharger le fichier CIF correspondant au materiau mp-9035 et d'étudier l’effet de 3 éléments de symétrie différents (pas l’identité) chacun pour 1 atome différent.

## 1.Télécharger le fichier CIF du matériau mp-9035

In [1]:
#Code permettant de créer le fichier CIF computed de la structure du NaLuS2 (mp-9035) 
from pymatgen.io.cif import CifWriter
from pymatgen.ext.matproj import MPRester
with MPRester("lTqZwmbprAgWB64c") as m:

    # Structure for material id
    structure = m.get_structure_by_material_id("mp-9035")
    w = CifWriter(structure)
    w.write_file('NaLuS2_computed.cif')

In [2]:
#Code permettant de créer le fichier CIF symmetrized de la structure du NaLuS2 (mp-9035)
from pymatgen.io.cif import CifWriter
from pymatgen.ext.matproj import MPRester
with MPRester("lTqZwmbprAgWB64c") as m:
    # Structure for material id
    structure = m.get_structure_by_material_id("mp-9035")
    w = CifWriter(structure,symprec=0.1)
    w.write_file('NaLuS2_symmetrized.cif')

## 2. Symétries

La structure cristalline du matériau mp-9035 possède 36 éléments de symétrie différents. Dans ce rapport, nous analyserons une rotation d'ordre 3 (n°5), un plan miroir (n°10) ainsi qu'une translation (n°13). Pour chacune de ces symétries, nous analyserons l'effet de celle-ci sur un atome de la cellule conventionnelle et nous l'illustrerons.

### 2.1 Axe de rotation d'ordre 3 sur un atome de Sodium

In [3]:
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer,SymmOp
import numpy as np
structure=SpacegroupAnalyzer(structure).get_symmetrized_structure()
C3=SymmOp.from_xyz_string("-x+y,-x,z") #Axe de rotation d'ordre 3 (symétrie numéro 5)
pos1Na=np.array([0,1,0.5],dtype=float) #Position de départ de l'atome de Na
print("Matrice de rotation : ")
print(C3.rotation_matrix)
print("Position de départ de l'atome de Na :",pos1Na)
print("Position d'arrivée de l'atome de Na : ", C3.operate(pos1Na))

Matrice de rotation : 
[[-1.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
Position de départ de l'atome de Na : [0.  1.  0.5]
Position d'arrivée de l'atome de Na :  [1.  0.  0.5]


Tout d'abord, considérons la symétrie numéro 5 de la structure cristalline du matériau mp-9035. Il s'agit d'un axe de rotation d'ordre 3. Il s'agit donc d'une rotation de 120°. L'axe de rotation est selon la direction $[001]$ et coïncide donc avec le vecteur de base $\vec{c}$. 
La matrice de rotation associée à cette symmétrie est la suivante : 

\begin{pmatrix} 
-1 & 1 & 0 \\
-1 & 0 & 0 \\
0 & 0 & 1 \\
\end{pmatrix}

Tout atome se situant en $(x,y,z)$ est envoyé en $(-x+y,-x,z)$ par cette symétrie. Considérons l'atome de Sodium (Na) positionné en $(0,1,1/2)$ . Par cette rotation d'ordre 3, son image se trouve en $(1,0,1/2)$.



$$
\begin{pmatrix}
-1 & 1 & 0 \\
-1 & 0 & 0 \\
0 & 0 & 1 \\
\end{pmatrix}
\begin{pmatrix}
0 \\ 
1 \\
0.5 \\
\end{pmatrix}=
\begin{pmatrix}
1 \\ 
0 \\
0.5 \\
\end{pmatrix}
$$

Trouvez ci-dessous la représentation de la symétrie sur cet atome de sodium. L'atome de sodium de gauche opaque a pour image celui plus clair par cette symétrie.

In [4]:
%%html
<tr>
    <td> <img src="C3Na.PNG" width="230"> </td>
    <td> <img src="C3Na120.PNG" width="230"> </td>
</tr>

Ces figures ont été générées par le site Jmol Crystal Symmetry Explore [1] à partir du fichier CIF symmetrized téléchargé sur Materials Project [2].

### 2.2 Plan miroir sur un atome de Soufre

In [5]:
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer,SymmOp
import numpy as np
structure=SpacegroupAnalyzer(structure).get_symmetrized_structure()
M=SymmOp.from_xyz_string("-x+y,y,z") #Plan miroir (symétrie numéro 10)
pos1S=np.array([1,1,0.26],dtype=float) #Position de départ de l'atome de Na

print("Matrice de rotation : ")
print(M.rotation_matrix)
print("Position de départ de l'atome de S :",pos1S)
print("Position d'arrivée de l'atome de S : ", M.operate(pos1S))

Matrice de rotation : 
[[-1.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
Position de départ de l'atome de S : [1.   1.   0.26]
Position d'arrivée de l'atome de S :  [0.   1.   0.26]


Ensuite, analysons la symétrie numéro 10 du matériau mp-9035. Il s'agit d'un plan miroir perpendiculaire à la direction $[2\overline{1}0]$. Sa matrice de rotation associée est : 

$$
\begin{pmatrix} 
-1 & 1 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{pmatrix}
$$

Tout point situé en $(x,y,z)$ aura comme image $(-x+y,y,z)$ par cette symétrie. Considérons l'effet de cette symétrie sur un atome de Soufre situé en $(1,1,0.26)$. Son image par cette symétrie est en $(0,1,0.26)$.

$$
\begin{pmatrix}
-1 & 1 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{pmatrix}
\begin{pmatrix}
1 \\ 
1 \\
0.26 \\
\end{pmatrix}=
\begin{pmatrix}
0 \\ 
1 \\
0.26 \\
\end{pmatrix}
$$

Ci-dessous, est représentée la symétrie dans la cellule conventionnelle de la structure cristalline. Le plan vert est le plan miroir, l'atome jaune opaque est l'atome de Soufre considéré et la flèche turquoise montre son image par cette symétrie.

In [6]:
%%html
<tr>
    <td> <img src="MS.PNG" width="350"> </td>
    <td> <img src="MS1.PNG" width="200"> </td>
</tr>



Ces figures ont été générées par le site Jmol Crystal Symmetry Explore [1] à partir du fichier CIF symmetrized téléchargé sur Materials Project [2].

### 2.3 Translation sur un atome de Lutécium

In [7]:
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer,SpacegroupOperations,generate_full_symmops,SymmOp
import numpy as np
structure=SpacegroupAnalyzer(structure).get_symmetrized_structure()
T=SymmOp.from_xyz_string("x-1/3,y+1/3,z+1/3") #Rototranslation (symétrie numéro 13)
#Lu en (1,0,1) 
pos1Lu=np.array([1,0,0],dtype=float) #Position de départ de l'atome de Na

print("Matrice de rotation : ")
print(T.rotation_matrix)
print("Vecteur de translation")
print(T.translation_vector)

print("Position de départ de l'atome de Lu :",pos1Lu)
print("Position d'arrivée de l'atome de Lu : ", T.operate(pos1Lu))

Matrice de rotation : 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Vecteur de translation
[-0.33333333  0.33333333  0.33333333]
Position de départ de l'atome de Lu : [1. 0. 0.]
Position d'arrivée de l'atome de Lu :  [0.66666667 0.33333333 0.33333333]


Enfin, analysons la symétrie numéro 13 du matériau mp-9035. Il s'agit d'une translation de vecteur $\left(\frac{-1}{3},\frac{1}{3},\frac{1}{3}\right)$. Sa matrice de transformation associée est la matrice identité : 

$$
\begin{pmatrix} 
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{pmatrix}
$$

Tout point situé en $(x,y,z)$ aura comme image $\left(x-\frac{1}{3}, y+\frac{1}{3},z+\frac{1}{3}\right)$ par cette symétrie. Considérons l'effet de cette translation sur un atome de Lutécium situé en $(1,0,0)$. Son image par cette translation est un atome de Lutécium situé en $\left(\frac{2}{3},\frac{1}{3},\frac{1}{3}\right)$.

$$
\begin{pmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{pmatrix}
\begin{pmatrix}
1 \\ 
0 \\
0 \\
\end{pmatrix} + 
\begin{pmatrix}
-1/3 \\ 
1/3 \\
1/3 \\
\end{pmatrix}
=
\begin{pmatrix}
2/3 \\ 
1/3 \\
1/3 \\
\end{pmatrix}
$$

Ci-dessous, est représentée cette translation dans la cellule conventionnelle de la structure cristalline. La flèche jaune représente la translation entre les deux atomes de Lutécium (atomes verts opaques)

In [8]:
%%html
<tr>
    <td> <img src="TL.PNG" width="120"> </td>
    <td> <img src="TLu.PNG" width="120"> </td>
</tr>

Ces figures ont été générées par le site Jmol Crystal Symmetry Explore [1] à partir du fichier CIF symmetrized téléchargé sur Materials Project [2].

## 3. Sources
[1]« Jmol Crystal Symmetry Explorer ». [En ligne]. Disponible sur: https://www.pslc.ws/jsmol/jcse/explore.htm. [Consulté le: 13-mars-2020].

[2]« Materials Project ». [En ligne]. Disponible sur: https://materialsproject.org/. [Consulté le: 19-février-2020].

[3] « Pymatgen Core Operations Module ». [En ligne]. Disponible sur: https://pymatgen.org/pymatgen.core.operations.html. [Consulté le: 11-mars-2020]. 

